networks:
  fabric:
    external: true

services:
  cli:
    image: hyperledger/fabric-tools:2.2.4
    container_name: cli
    tty: true
    working_dir: /opt/home
    environment:
      - FABRIC_CFG_PATH=/opt/home/config
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
    volumes:
      - /var/run/:/host/var/run
      
      - ./config:/opt/home/config # Configs
      - ./artifacts:/opt/home/artifacts # Artifacts
      - ./chaincode:/opt/home/chaincode # Chaincode

      - ./crypto/ordererOrganizations/example.com/orderers/orderer.example.com:/opt/home/orderer # Orderer

      - ./crypto/peerOrganizations/org1.example.com/msp:/opt/home/org1/root/msp # Root Org1 MSP
      - ./crypto/peerOrganizations/org1.example.com/peers:/opt/home/org1/peers # Peers
      - ./crypto/peerOrganizations/org1.example.com/users:/opt/home/org1/users # Users

      - ./crypto/peerOrganizations/org2.example.com/msp:/opt/home/org2/root/msp # Root Org2 MSP
      - ./crypto/peerOrganizations/org2.example.com/peers:/opt/home/org2/peers # Peers
      - ./crypto/peerOrganizations/org2.example.com/users:/opt/home/org2/users # Users
    networks:
      - fabric